version: '3'

services:
  backend: 
    build: .
    volumes:
      - ./:/home/sprintcrowd/
    depends_on:
      - database
    ports:
      - 80:80
  
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: sprintcrowd
      POSTGRES_PASSWORD: Admin123
      POSTGRES_DB: SprintCrowd
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080